[master]
  runner = "s3://ambiata-dist/master-ambiata/master-haskell-library-0.0.1-20151210220945-684de5a"
  version = 1
  sha1 = "5a89a62ecfc4b66300436840c53c7f643ffec707"

[build.dist]
  HADDOCK = "true"

[build.branches]
